name: Run Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.8", "3.9"]

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - name: Install GStatSim
        run: |
          python3 setup.py install
          pip install pytest
      - name: Run tests
        run: pytest